namespace Core.Contracts;

/// <summary>
/// Represents the response generated by a large language model (LLM).
/// </summary>
/// <remarks>This class encapsulates the content returned by an LLM, typically in the form of a textual
/// response.</remarks>
public interface ILlmMessage
{
    /// <summary>
    /// Gets or sets the content of the message.
    /// </summary>
    public string Role { get; set; }

    /// <summary>
    /// Gets or sets the collection of messages.
    /// </summary>
    public string Content { get; set; }
}
