namespace Core.Enums;

/// <summary>
/// Defines the dimensional sizes of various embedding models used in natural language processing.
/// </summary>
/// <remarks>This enumeration provides predefined values representing the number of dimensions for
/// embeddings  generated by different models, such as OpenAI, Cohere, and SBERT. These dimensions are critical  for
/// understanding the structure and compatibility of embeddings in machine learning applications.</remarks>
public enum OpenAIEmbeddingDimensions
{
    /// <summary>
    /// Represents the size of the small embedding model, measured in dimensions.
    /// </summary>
    /// <remarks>text-embedding-3-small and text-embedding-ada-002</remarks>
    Embedding3Small = 1536,

    /// <summary>
    /// Represents the size of a large embedding, measured in the number of dimensions.
    /// </summary>
    /// <remarks>text-embedding-3-large</remarks>
    TextEmbedding3Large = 3072,

    /// <summary>
    /// Represents the size of a large embedding, measured in the number of dimensions.
    /// </summary>
    /// <remarks>Example for Cohere models</remarks>
    CohereEmbed = 1024,

    /// <summary>
    /// Represents the size of a large embedding, measured in the number of dimensions.
    /// </summary>
    /// <remarks>SBERT model: all-MiniLM-L6-v2</remarks>
    SbertMiniLM = 384,

    /// <summary>
    /// Represents the size of a large embedding, measured in the number of dimensions.
    /// </summary>
    /// <remarks>SBERT model: all-mpnet-base-v2</remarks>
    SbertMpnetBase = 768
}
